### ISSUE TITLE
Scrub build and os artifacts from gitignore

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#10]
Make sure AS on Linux doesn't add anything gross.

**Comment by reustonium** [comment]
1) update your repo
2) perform a gradle sync (from menu bar)
3) run `gradle build`
4) check that nothing new shows up via `git status`
4a) `>>.gitignore` anything that shows up

**Comment by thequbit** [comment]
Couldn't get this working on Ubuntu ... finally just caved and installed on Windows box.  As expected nothing showed up.  Will keep open until I can try on another machine with Ubuntu.

**Comment by thequbit** [comment]
I'm closing this, since I haven't had any issues on Windows or Ubuntu.
