### ISSUE TITLE
Create Splash Activity

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#11]

**Comment by thequbit** [comment]
Here is the location of the ones that @aztec8 put together:

https://github.com/hhroc/yellr/tree/master/src/app/splash-screens/android

**Comment by reustonium** [comment]
yep, I've already imported all the style colors into android resources.  Should have this done shortly

**Comment by reustonium** [comment]
haven't found the text-font name yet, but was planning on using roboto, per the google design docs.  It's an easy update down the road if you want it switched.

**Comment by reustonium** [comment]
closed with pull request #13
