### ISSUE TITLE
Time decode for stories doesn't appear to be working 

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#119]
Always shows 'a moment ago'.

**Comment by thequbit** [comment]
It says "Moments ago".

**Comment by reustonium** [comment]
the debug release looks fine, we need to find a better way to test the release version on emulators.

I can't installed an unsigned `assembleRelease` build on my device to test it out.

but you are right whatever version of the code is built and distributed on yellr.net right now only shows "moments ago"

**Comment by thequbit** [comment]
Submitted via the Yellr app:

![](https://yellr.net/media/66bce9ab-7833-4bf0-a17c-4e864a40a208p.jpg)

**Comment by thequbit** [comment]
This was my fault.  I thought i had the fractional second on the response from the server, however I was stripping it out.  Closed with #132 .
