### ISSUE TITLE
Create icon

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#12]
The cordova app had a nice icon.  Should bring that over to this native android app.

**Comment by reustonium** [comment]
can't seem to find any launcher icons here... https://github.com/hhroc/yellr/tree/master/src/app

**Comment by thequbit** [comment]
@zapo sent them to me.  Emailed them to you.  Also it is Helvetica Neue for the font.

**Comment by reustonium** [comment]
closed with pull request #13
