### ISSUE TITLE
After posting,  hitting the back key brings the user back to the post activity/fragment 

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#124]
@reustonium any insight to this?

**Comment by reustonium** [comment]
Yeah probably need to remove this from the backstack upon post.

The thought was that if the post was unsuccessful they  could get back
easily.

**Comment by thequbit** [comment]
How do we remove it from the history list?  This is the same thing as #127.

**Comment by thequbit** [comment]
Closed in #131
