### ISSUE TITLE
Integrate Font-Awesome for Android

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#14]
The existing app uses FA fonts for all of the buttons, this blog post describes how to use FA in a native android app.

http://www.eldelshell.com/font-awesome-icons-in-android.html

**Comment by reustonium** [comment]
Here's the cheatsheet to select only the necessary icons.

https://fortawesome.github.io/Font-Awesome/cheatsheet/

**Comment by thequbit** [comment]
:+1:

**Comment by reustonium** [comment]
closed via PR #31
