### ISSUE TITLE
Implement poll question type, and display results.

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#146]
Should implement 'poll' question type (rather than 'multiple choice'), and make those poll results available (and displayed) immediately.

**Comment by thequbit** [comment]
We'll make this for 0.1.9.

**Comment by dkd903** [comment]
Waiting on the API endpoints for Poll.

**Comment by thequbit** [comment]
@dkd903 I believe the [get_assignments.json](https://github.com/hhroc/yellr-server/wiki/get_assignments.json) end point should return the correct information if a poll question type is selected when creating the assignment.

What is currently missing is the results from the poll ( there is no way to get that information right now ).  I'll work on getting that in place.

**Comment by dkd903** [comment]
Still not done - API return empty results
