### ISSUE TITLE
Resize image on android client before upload

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#154]
There is no reason why we need a 4k x 2k image on the server ... we're currently using imagemagick to resize it, and it's taking too long.  We should do it on the android device.

This should be good:
http://stackoverflow.com/questions/3331527/android-resize-a-large-bitmap-file-to-scaled-output-file

**Comment by thequbit** [comment]
@dkd903 did this make it in to your last PR?

**Comment by dkd903** [comment]
No. Made a commit today. Will be in next PR.
