### ISSUE TITLE
Update StoriesFragment ListView

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#17]
Alter StoriesFragment to display a listView, pulling data from the server.  

http://www.vogella.com/tutorials/AndroidListView/article.html

**Comment by thequbit** [comment]
Were you thinking `ExpandableListView` for this?  An assignment has a `question_text` as well as 'description' fields.  `question_text` could be displayed as the default, and then the expansion could be 'description'.

Thoughts?

**Comment by reustonium** [comment]
yeah thats one good way of showing this info, if there is also media associated with a story it might be nice to use a simple `ListFragment` with a custom adapter.

Then you could have the thumbnail on the left, a title to the right, and a description below it.

![image](https://cloud.githubusercontent.com/assets/1432186/6060929/d014e2ee-ad10-11e4-9910-519b5aec62b6.png)

**Comment by thequbit** [comment]
Assignments won't have media (for now),  however stories will have a
picture associated with each story, so that will work out well.

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
herm, this is not as simple as I thought it would be (note: this is because I'm lost not because it's actually hard, ha).  Will continue to hack away at it.

**Comment by thequbit** [comment]
@reustonium In what package should the .XML and .java files for this live?  Under activities? fragments? something new?

**Comment by reustonium** [comment]
all layout xml lives under `/res/layout`
the java files should remain [here](https://github.com/hhroc/yellr-android/tree/master/app/src/main/java/yellr/net/yellr_android/fragments)

Again not a perfect example but here is the lunchpals way
`PangsListFragment` [link](https://github.com/reustonium/Lunch-Pals/blob/master/lunch-pals/src/main/java/com/reustonium/lunchpals/fragments/PangsListFragment.java)

`PangsListFragment` layout xml (this is the entire fragment's layout) [link](https://github.com/reustonium/Lunch-Pals/blob/master/lunch-pals/src/main/res/layout/fragment_home.xml)

`PangsListFragment` row layout xml (this formats the indivudal row) [link](https://github.com/reustonium/Lunch-Pals/blob/master/lunch-pals/src/main/res/layout/fragment_home_row.xml)

**Comment by thequbit** [comment]
That ... that was a bit painful.

https://github.com/hhroc/yellr-android/pull/22

Creates and populates lists for assignments and stories.  Needs some styling, but that can be done later on.

@reustonium give it a review and let me know.  It's hard-coded to talk to http://yellr.mycodespace.net/ at the moment.  I'll leave the server running so you can give it a test.

http://yellr.mycodespace.net/static/bin/app-debug.apk also is the latest binary if you would like to grab that.

**Comment by reustonium** [comment]
closed by #22
