### ISSUE TITLE
Don't use jars in repo, but pull them from mavenCentral / jCenter

### ISSUE THREAD

**Issue by ghost** [hhroc/yellr-android#172]

**Comment by thequbit** [comment]
I wasn't aware of the centralized packing,  I'll make the switch tonight. 

Thanks Boris!

**Comment by thequbit** [comment]
@krt16s we're demoing at LibrePlanet tomorrow, any chance we could get into the F-droid store before then if I close this ticket? 

Thanks again for the feedback!

**Comment by ghost** [comment]
Looking at your timezone I don't think we can make it. Builds start about 0100~0200 UTC once a day. Sorry :/

**Comment by thequbit** [comment]
@krt16s no worries at all!

Thank you so much for the feedback on the Maven Central suggestion.  The fix has been implemented here:
https://github.com/thequbit/yellr-android/commit/082717f5dee59c12c90007c4561d58527664041f

And the tag for v0.1.5 is here:
https://github.com/hhroc/yellr-android/releases/tag/v0.1.5

Close at your leisure :).

Edit: fixed build number issue.  Tag now updated.

**Comment by thequbit** [comment]
Yikes, forgot to change the build number.  Recreating tag.

**Comment by ghost** [comment]
Added. One minor thing: I added "GPLv2 and later" as license, since you use Apache2 libraries which are incompatible with plain GPLv2. Is this correct?

**Comment by thequbit** [comment]
@krt16s to you question, I do believe that is correct.  We'll talk to those with more experience that us in the field of licensing and get back to you.  I think changing it to "GPLv2 and later" is good for now.

Thoughts on when it will be pulled into the build cycle?

Thanks again for all your input!

**Comment by ghost** [comment]
It's available in FDroid now.
