### ISSUE TITLE
Change notification icon to black and white

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-android#177]
Some devices don't display color notification icons.

**Comment by thequbit** [comment]
This should be for all notifications (new assignment, new story, new message).

**Comment by thequbit** [comment]
This needs to be fixed in 0.1.8.  It looks terrible on Android 5.0.  The Icon should just be a Y I think.

**Comment by thequbit** [comment]
@dkd903 we talked about this at lunch the other day - the icon doesn't render correctly.  Don't burn too much time on this, but if you can fix it that would be awesome.

**Comment by dkd903** [comment]
Fixed - http://stackoverflow.com/questions/28387602/notification-bar-icon-turns-white-in-android-5-lollipop
![screenshot_2015-08-13-01-17-25](https://cloud.githubusercontent.com/assets/233879/9243048/41103124-4159-11e5-9977-1d4fdd720622.png)
![screenshot_2015-08-13-01-05-42](https://cloud.githubusercontent.com/assets/233879/9243050/448673c2-4159-11e5-8d84-0b5dd583ecc7.png)
![screen shot 2015-08-13 at 1 18 15 am](https://cloud.githubusercontent.com/assets/233879/9243052/4d3cd4ac-4159-11e5-8d0d-4b0ed63ff7be.png)
