### ISSUE TITLE
Implement Split Actionbar

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#19]
The current app makes nice use of bottom screen space to provide additional action buttons (image, video, text, etc) we should follow the same design by using a split actionbar.

**Comment by reustonium** [comment]
This type of design really doesn't fit into the 'Android Design' paradigm.  Ideally all 4 story types would be launched from a single "new story" button (FAB or Action Button).

**Comment by thequbit** [comment]
Possible wrong vocabulary used here...  By story do you mean post?

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by reustonium** [comment]
Yes, my mistake a post.

The `SplitActionBar` by design pushes all action buttons to the bottom of the screen on narrow devices.  The legacy app keeps some of the buttons on the actionbar and some down below.

I would argue that the actionbar's primary action button is for a 'new post', and that the `PostActivity` can handle what media get's attached. @thequbit what do you think?

**Comment by thequbit** [comment]
I thought no that makes sense, yea.   Let me pull down the code and see
what it looks like when rendered.

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
I really like this flow.   Closing.
