### ISSUE TITLE
Formatting is broken on fragment_post.xml 

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#194]
The formatting is all messed up on the post page.  I think this is due to a bad merge?

http://i.imgur.com/ddQxlKN.png

I can't type anything ( because the text box is too low ), and the preview image doesn't come up.  Also, there are duplicate id's in that file ...

**Comment by dkd903** [comment]
I saw this issue earlier today. Have fixed it. Will send a pr

**Comment by thequbit** [comment]
I believe this is closed, yes? @dkd903

**Comment by dkd903** [comment]
Fix was added in the 0.1.8 release.
