### ISSUE TITLE
Create MainActivity

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#2]
This will have an action bar on top, with two tabs: View Assignments and View Stories.  This will also have a way to create a new 'free post' somewhere on the screen (select from text, picture, video, audio).

@reustonium to make some decisions on how this will look.  Will keep color scheme similar to that of existing YellR app.  Color: #FFCF13

**Comment by thequbit** [comment]
I pulled your changes as of ~9pm ET last night, and things look good!

There are three tabs (sections?) on top, rather than two.  I presume this was just a starting point.  I think we're going to want to stick to two tabs, one for assignments and one for stories.  We have talked about having 'posts in your area' kind of thing, but that requires quite a bit more work on the moderator side of things.

The first tab should be 'Assignments' where a user can view the list of active assignments.  When clicking on an assignment, it will either expand it to display more details, or go to a new screen where it is displayed with full detail (we go to a different screen today with the cordova version).

With stories, it should be a list of current stories, where some preview text could be displayed on selection.  Then the full story should be displayed in a different screen.  Note: I would be okay with the story launching the URL to itself in a brower for now, so we don't have to worry about rendering HTML inside the app.

@reustonium thoughts?

**Comment by reustonium** [comment]
that all sounds good, I need to scrap the existing MainActivity due to that issue I mentioned last night with Android Studio and support libraries.  This activity will have 2 tabs like you describe.

**Comment by thequbit** [comment]
Gotcha.
Idea on timeline? No rush, just want to keep the team updated.
I'll work on #9 in the meantime.

**Comment by reustonium** [comment]
I think this can be closed by PR #16, thoughts?

**Comment by thequbit** [comment]
Sure does!

Closing.
