### ISSUE TITLE
Style entries in assignments and stories lists

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#23]
Need some of that sweet, sweet styling for our lists.

**Comment by thequbit** [comment]
@reustonium are you going to take this on?  If you point me to some docs I could do it, however at the moment I'm a bit lost as to where to start.  It seems kind of CSS like, but in XML format.  Let me know.

**Comment by reustonium** [comment]
i'll take the first stab at it

**Comment by thequbit** [comment]
Don't go crazy, if anything just having all of the fields to tweak in the XML files is a great start.  I'm sure we're going to get a lot of feedback on visual appearance from the other HHRoc folks, especially our UX guy.  Thanks for taking a crack at it!
