### ISSUE TITLE
Create view assignment Activity

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#24]
Need a new activity to display an assignment and it's information.  This then needs a "contribute" button on it, which will go to the 'publish post' activity.

**Comment by thequbit** [comment]
Will display Assignment Question, and question description.  Should also display who posted it, and it's due date.  There needs to be a button that allows the user to contribute to that assignment (Launch an Intent for PostActivity with putExtra of the assignment id).

**Comment by thequbit** [comment]
Got this hooked up in https://github.com/thequbit/yellr-android/commit/a01c598ea87a5a6bc1368a6ef219f5e02a1880fb

Contribute button passes the assignmentId with the Intent to the PostActivity, so it can be included with the HTTP POST to publish_post.json.

Will do a PR once @reustonium finishes up the Post stuff and confirms correct operation.

**Comment by thequbit** [comment]
Looks like this is going to get pulled out for the first version of the app,  and we'll just launch the PostActivity from the ViewAssignments fragment. 

Leaving open,  until that flow is implemented, then will close and Mark as non-implemented

**Comment by reustonium** [comment]
closed by #54
