### ISSUE TITLE
Create Publish Post activity

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#26]
Need a new activity to create a new post.  Let's keep this simple for the first round of this app and just have it be a picture.

We'll need to fire the 'take a picture' or the 'select a picture' things to get the content for the upload_media.json call as well (I haven't a clue how to do this ...).

**Comment by thequbit** [comment]
I think this is closable, yes @reustonium ?  Or are you going to close it after you clear the fields, notify user, and return to HomeActivity?

Additionally, if we are responding to an assignment, we may want to return to the assignment rather than go to the HomeActivity.  My assumption is that we are simply just 'leaving' the post activity, not directing to another one (so the back button works correctly).

**Comment by reustonium** [comment]
I maintain that viewing a single assignment is redundant.  We can close this issue since I created a new issue for handling the 'after' post workflow, let's take that discussion there. #46
