### ISSUE TITLE
App creates two icons when installed

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#39]
The app creates two icons in the apps list when installed.  They both appear to do the same thing.

**Comment by reustonium** [comment]
I believe the second icon is an artifact on the installed device from when I updated the application name. If you performed a clean install, I expect a single icon.

**Comment by reustonium** [comment]
I'll investigate to confirm

**Comment by thequbit** [comment]
I restarted the emulator thinking that would be enough.   I uninsalled the
app on the emulator and reinstalled.   The two icons came back.

-TD

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
Confirmed when installed on my HTC One M7 that two icons were created.

**Comment by thequbit** [comment]
:+1:
