### ISSUE TITLE
PublishPostIntentService GSON Issue

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#42]
Stringifying the MediaObjects JSON to pass to the service via putExtras(string) isn't necessary, and is actually a lot more complicated than the alternatives.

The current method requires:
1. creating a MediaObjectsDefinition Object 
2. setting the properties
3. using gson.toJson
4. putExtra(newJsonString)

This causes bugs when getExtras finds a single media object rather than an array.

Since communicating between the fragment and intentService doesn't really need any JSON it would be way cleaner and much faster to make MediaObjectsDefinition implement [Parcelable](https://developer.android.com/reference/android/os/Parcelable.html) this makes for a nice way to pass the media object(s) to the service without any JSON BS.

**Comment by thequbit** [comment]
In my opinion we should ignore anything json with regard to the media_objects field within publish_post.json.

Just sent the parameter that you pass to the media_objects field to:

```
["<media_object_id>"] 
```

Where media_object_id is the string returned in the media_object_id field within the response from upload_media.json.

Generate the json by hand for the field. In the future of we support additional mediaobjects per post,  we'll extend the method to take an array and return the appropriate string. 

Does that make sense?

**Comment by thequbit** [comment]
Note: above was edited ^^

**Comment by reustonium** [comment]
yeah thats what I'm doing now, running into some issues in the PublishPostIntentService, during media upload.

**Comment by reustonium** [comment]
gonna have to call it quits soon, maybe you can take a look tonight, I'll create a new issue with line numbers and problem definition.

**Comment by thequbit** [comment]
sounds good.  push and open a ticket, or comment here where it's bombing out and I'll take a look tonight.

**Comment by thequbit** [comment]
Looks like this is connected to #43, and probably can be closed after that is closed.  I would like to revisit how we're doing that with the gson object, but if it works we can let it ride for the moment.

**Comment by reustonium** [comment]
agreed on letting it stay if it's working.  I also recommended the most painful java JSON lib. I meant to recommend Jackson, not GSON. My bad.

**Comment by thequbit** [comment]
haha, classic.  No worries.
