### ISSUE TITLE
Render story markdown on view story page

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#44]
I assume we'll need to use a library like this one:

http://uncodin.github.io/bypass/:

**Comment by thequbit** [comment]
https://github.com/Uncodin/bypass/issues/158

I don't think bypass is the right option for us, since it looks to be written in C and needs to be compiled.

I think we'll just send the pre-rendered HTML to the device, and display the HTML in the TextView:

http://stackoverflow.com/questions/2116162/how-to-display-html-in-textview

It's a solid solution, with a quick implementation.

**Comment by thequbit** [comment]
There are,  as one can imagine, a number of gotchas when doing HTML rendering. 

I implemented WebView with good success,  however we'll need to add some css to ensure images are displayed correctly.

**Comment by reustonium** [comment]
I'd be weary of WebView, it's been the most common source of Android Vulnerabilities in the past.

**Comment by thequbit** [comment]
Herm, alright.  It didn't look like there was a good way to do pictures in TextView, however I may not have dug deep enough.

I won't submit the PT with the WebView stuff in there then.

Thanks @reustonium

**Comment by thequbit** [comment]
I'm thinking WebView may be our answer after all, just with some sanitizing before hand.  After inquiring with those who are a bit more in-the-know, if the HTML is coming over HTTPS, the chance of injection is minimized (although, not zero).  We can do a .replace() for '<script>' to make it safer as well.

I'm going to implement, and push.

**Comment by thequbit** [comment]
Implemented within #73
