### ISSUE TITLE
Assignment_ID is not being set properly from AssignmentsListFragment

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#48]
Find out why...

**Comment by reustonium** [comment]
`PostFragment` is getting called from `AssignmentsFragment` without a `Bundle`, i.e. `assignementID` is not getting passed.  Investigating further...

**Comment by reustonium** [comment]
Ugh, what a pain in the ass.  Need to implement the `.NewInstance` design pattern.  The PostActivity still recieves the intent (including the `assignmentID`) then when the PostFragment is created it should call the `.NewInstance` method and take the `assignmentID` as a parameter. 

This all happens because the Intent only launches the Activity, when the Fragment get's made it loses the intent.  I had to implement this design pattern in previous apps but somehow forgot about it.

**Comment by thequbit** [comment]
Any option to save it to the shared preferences as the "current assignment
id" as a hack?

What kind of effort is associated with the conversion?

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by reustonium** [comment]
I'm about 30% done, this is the right design pattern.  It'll show up many other places in this app.

**Comment by reustonium** [comment]
PR #49 fixes this bug.
