### ISSUE TITLE
Implement "pull down to refresh"?

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#59]
@reustonium how hard is it to implement the 'pull down to refresh' on all of the list fragments?

**Comment by reustonium** [comment]
medium, but necessary i think.

**Comment by thequbit** [comment]
Not a high priority at the moment.  Opening and closing the app fires the
events needed to refresh, and i'll (hopefully) have the service done soon
so new assignments/stories/messages/notifications will come in
automatically.

On Tue, Feb 10, 2015 at 9:21 AM, Andy Ruestow notifications@github.com
wrote:

> medium, but necessary i think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hhroc/yellr-android/issues/59#issuecomment-73706226.

## 

_Tim Duffy_
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by reustonium** [comment]
closed by PR #66
