### ISSUE TITLE
Change date/time display for times less than 15 minutes

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#60]
So there will be some differences in time between the server and the mobile device being used.  Because of this, we can get "-1 minutes ago." on the app.  We should change it to anything less than 15 minutes (including date/times in the future), should be "just now" instead of "n minutes ago."

**Comment by reustonium** [comment]
sounds good, there is almost certainly going to be some timezone issues that are currently unhandled.

**Comment by thequbit** [comment]
oh man ... yea good point.

Switch everything to GMT then?  I think that probably makes the most sense ...

@Nolski ya want to chime in on this?

**Comment by reustonium** [comment]
Timezones are the worst, I wish we just went to global GMT.  I have no problem working my straight job from 1230z-2130z.  

If we make this change at the same time as the metric system, people won't even complain about going metric. /rant

**Comment by thequbit** [comment]
I ... I don't .. I don't know what repo to open the 'move the US to metric' issue in ...

**Comment by reustonium** [comment]
[bootstrap](https://github.com/twbs/bootstrap) has the most star's by far, start there?

:earth_americas:

**Comment by reustonium** [comment]
opened a new question for timezone questions #63,  This can be closed pending the merge of PR #62

**Comment by reustonium** [comment]
closed by PR #62
