### ISSUE TITLE
Require Camera?

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#65]
I'm not sure it's a good idea to set `required=true` for the camera `uses-feature`.

Found in the manifest...
`<uses-feature android:name="android.hardware.camera" android:required="true" />`

This requirement would prevent any user from even loading the app on their phone if they don't have a camera.  I know most phones have a camera these days, but I'd think that we would still want to welcome users who don't have a camera.

Thoughts? @thequbit

**Comment by thequbit** [comment]
100% agree.   That push was kind of mid-thought.  I wasn't able to get
permissions and I thought it was a camera issue,  but it's definitely a
storage issue.

Will pull out before submitting PR to upstream.

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by reustonium** [comment]
closed by PR #66
