### ISSUE TITLE
Analytics? 

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#75]
As a user I think analytics are pretty grimy. As a dev they can be helpful. What are your thoughts on either using analytics for the beta or having it be opt in only?

**Comment by thequbit** [comment]
So we capture quite a bit of data on the server side in the ClientLogs table in the database about how endpoints are being used.  As for app-side analytics, i think they could be valuable, but would diverge from the vision of the project.  I think we'll keep those out for now, and continue to ask that our alpha users fill out the survey we developed.

**Comment by reustonium** [comment]
sounds good, glad to hear the project supports users privacy!
