### ISSUE TITLE
Splash screen too long?

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#76]
If i'm seeing something i want to share ASAP, the splash screen may be a bit long.  I say we do 2 seconds for first boot, and .5 seconds for every other.  Thoughts @reustonium ?

**Comment by reustonium** [comment]
I think there's little value in varying the time. Might as well just make
it 500ms all the time.

**Comment by thequbit** [comment]
Sounds good to me.  I'll include on next PR.

**Comment by thequbit** [comment]
Closed in #80.  changed to .5 seconds.
