### ISSUE TITLE
Create Play Store Listing

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-android#92]
https://play.google.com/apps/publish/

**Comment by thequbit** [comment]
Name: Yellr
Short Description: Community Engagement App
Long Description: (TBD)

Application type: Applications
Category: Communication
Content rating: Everyone

Website: http://yellr.net/
Email: yellrdev@gmail.com
Phone:

**Comment by reustonium** [comment]
nice!

**Comment by thequbit** [comment]
Need to submit screen shots still, but getting there!

**Comment by reustonium** [comment]
might want to look at that short description

**Comment by thequbit** [comment]
dat copy pasta

**Comment by thequbit** [comment]
Done!
